# Generated by Django 4.1 on 2022-09-18 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_alter_watchlist_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watched',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='release_date',
            field=models.CharField(max_length=100),
        ),
    ]
