# Generated by Django 4.1 on 2022-09-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0003_watchlist_watched_alter_watchlist_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watched',
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='release_date',
            field=models.DateField(),
        ),
    ]
