# Generated by Django 4.1 on 2022-09-18 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0004_remove_watchlist_watched_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
