# Generated by Django 4.1 on 2022-09-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0005_watchlist_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='review',
            field=models.URLField(),
        ),
    ]
